"""
Django settings for myrecommendations project.

<<<<<<< HEAD
Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
=======
Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
>>>>>>> 314c1e3cfd5a2a31dc8fb54eb7c4bce031b4f13f
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

<<<<<<< HEAD
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vylzaaaafz%l-7*l(voqwvg1$+bzxw7@rrj#h-^$5x@1bedtd*'
=======

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'sbysh93a%0nl59*2q-c^f&^-1-n$mjewla$m*yd(x0o**$q9rk'
>>>>>>> 314c1e3cfd5a2a31dc8fb54eb7c4bce031b4f13f

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myrestaurants',
]

<<<<<<< HEAD
MIDDLEWARE_CLASSES = [
=======
MIDDLEWARE = [
>>>>>>> 314c1e3cfd5a2a31dc8fb54eb7c4bce031b4f13f
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
<<<<<<< HEAD
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
=======
>>>>>>> 314c1e3cfd5a2a31dc8fb54eb7c4bce031b4f13f
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myrecommendations.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myrecommendations.wsgi.application'


# Database
<<<<<<< HEAD
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases
=======
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
>>>>>>> 314c1e3cfd5a2a31dc8fb54eb7c4bce031b4f13f

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
<<<<<<< HEAD
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators
=======
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators
>>>>>>> 314c1e3cfd5a2a31dc8fb54eb7c4bce031b4f13f

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
<<<<<<< HEAD
# https://docs.djangoproject.com/en/1.9/topics/i18n/
=======
# https://docs.djangoproject.com/en/1.10/topics/i18n/
>>>>>>> 314c1e3cfd5a2a31dc8fb54eb7c4bce031b4f13f

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<< HEAD
# https://docs.djangoproject.com/en/1.9/howto/static-files/
=======
# https://docs.djangoproject.com/en/1.10/howto/static-files/
>>>>>>> 314c1e3cfd5a2a31dc8fb54eb7c4bce031b4f13f

STATIC_URL = '/static/'
